{
  try {
    close();
  }
 catch (  IOException exception) {
    Logging.unexpectedException(LOGGER,getClass(),"close",exception);
  }
}
