{
  try {
    action(e);
  }
 catch (  Throwable t) {
    ExceptionReporter.show(t);
  }
}
